# The name of the label to apply when an issue does not have all tasks checked
labelName: "status: needs-more-info"

# The color of the label in hex format (without #)
labelColor:

# The text of the comment to add to the issue in addition to the label
commentText: >
  Hi! This needs more information. Check out this [link](https://stackoverflow.com/)!

# Whether or not to ensure all checkboxes are checked
checkCheckboxes: true

# Keywords to look for in the body of the issue
keywords:
  - Describe the bug
  - To Reproduce
  - Expected behavior
  - Screenshots
